### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by saravanan-ppounds** [selbil/mail-queue#1]
Hi,

As per PHP 7 requirements, Short Tags "<?" is removed. Ensure this package is compatible  with PHP 7.

**Comment by emredoganm** [comment]
Is there any article for that because I am testing it on PHP7 and I researched PHP.net documentation but did not found anything about short open tags

**Comment by saravanan-ppounds** [comment]
Sorry, It is my server config.. But short tags are not encouraged. If it is removed, it will be helpful.

**Comment by saravanan-ppounds** [comment]
Kindly add comment if you removed short tags.

**Comment by emredoganm** [comment]
I removed short tags. Thank you so much @saravanan-ppounds
