### ISSUE TITLE
Send After bug?

### ISSUE THREAD

**Issue by seigieu** [selbil/mail-queue#2]
protected $queueSQL = "SELECT * FROM `::table-name::` WHERE
        (is_sent = 0 OR (is_sent = 1 AND try_again = 1 AND has_error = 1))
        AND (send_after >= '::now::' || send_after IS NULL) 
       ORDER BY created_at,updated_at LIMIT ::limit::";

Are you sure it shouldn't be `send_after < '::now::' ` instead of `(send_after >= '::now::' `
If send_after is future date it is always bigger than now and if NOW passes current date it will never be executed.

**Comment by emredoganm** [comment]
This query helps to find mail sets which set to send after now and add them in the next queue. I mean this is not a bug, and it is working, if you still face a new error, PRs are welcome.

**Comment by seigieu** [comment]
At the start, sorry i did not reply earlier - did not notice email.
I assume (maybe I'm wrong here) send_after allows us to set delay - am I wrong? 

If not, then Let's simplify it to basic numbers - let's say Hours. Assume Now is 10 and send after is 20;

    WHERE 20 >= 10; // passes 20 is bigger than 10

Let's wait  to 23

    WHERE 20 => 23 // Does not pass... 

Meaning it populate queue until that time. So in this case `send_later` 

Or either name is misleading.

By me `send_after` currently works as limiter: Send only till 20 and stop sending later.

**Comment by seigieu** [comment]
<?php
	/**
	  protected $queueSQL = "SELECT * FROM `::table-name::` WHERE
		(is_sent = 0 OR (is_sent = 1 AND try_again = 1 AND has_error = 1))
		AND (send_after >= '::now::' || send_after IS NULL) 
	   ORDER BY created_at,updated_at LIMIT ::limit::";
	 */
	 
	$databse_date = '2018-10-05';
	for($i = 1; $i <= 10; $i++){
		$date_now = date('Y-m-d',strtotime('2018-10-'.$i));
		echo "Date Check $databse_date >= {$date_now} ". ($databse_date >= $date_now ? 'Select item' : 'Do not select item') ." <br>\r\n";
		
	}

	for($i = 1; $i <= 10; $i++){
		$date_now = date('Y-m-d',strtotime('2018-10-'.$i));
		
		echo "Date Check $databse_date < {$date_now} ". ($databse_date < $date_now ? 'Select item' : 'Do not select item') ." <br>\r\n";
	}

Output

	Date Check 2018-10-05 >= 2018-10-01 Select item <br>
	Date Check 2018-10-05 >= 2018-10-02 Select item <br>
	Date Check 2018-10-05 >= 2018-10-03 Select item <br>
	Date Check 2018-10-05 >= 2018-10-04 Select item <br>
	Date Check 2018-10-05 >= 2018-10-05 Select item <br>
	Date Check 2018-10-05 >= 2018-10-06 Do not select item <br>
	Date Check 2018-10-05 >= 2018-10-07 Do not select item <br>
	Date Check 2018-10-05 >= 2018-10-08 Do not select item <br>
	Date Check 2018-10-05 >= 2018-10-09 Do not select item <br>
	Date Check 2018-10-05 >= 2018-10-10 Do not select item <br>
	Date Check 2018-10-05 < 2018-10-01 Do not select item <br>
	Date Check 2018-10-05 < 2018-10-02 Do not select item <br>
	Date Check 2018-10-05 < 2018-10-03 Do not select item <br>
	Date Check 2018-10-05 < 2018-10-04 Do not select item <br>
	Date Check 2018-10-05 < 2018-10-05 Do not select item <br>
	Date Check 2018-10-05 < 2018-10-06 Select item <br>
	Date Check 2018-10-05 < 2018-10-07 Select item <br>
	Date Check 2018-10-05 < 2018-10-08 Select item <br>
	Date Check 2018-10-05 < 2018-10-09 Select item <br>
	Date Check 2018-10-05 < 2018-10-10 Select item <br>
